services:
  db:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quizlet
    ports:
      - 5432:5432
  db-redis:
    image: redis:7.0.11
    ports:
      - 6379:6379
  storage:
    image: minio/minio
    command: minio server /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin